config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  resources :users, only: [:index, :show] 
  resources :leave_application_requests

  root 'users#show'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :leave_application_requests
  enum role: [ :employee, :reporting_head ]
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  # protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  def new
    super
  end

  # POST /resource/unlock
  def create
    super
  end

  # GET /resource/unlock?unlock_token=abcdef
  def show
    super
  end

  # protected

  # The path used after sending unlock password instructions
  def after_sending_unlock_instructions_path_for(resource)
    super(resource)
  end

  # The path used after unlocking the resource
  def after_unlock_path_for(resource)
    super(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    redirect_to new_user_session_path and return if !user_signed_in?
    @user = User.find(params[:id])
    @leave_application_requests = []
    @leave_application_requests = @user.leave_application_requests.where(active: 1) if @user.leave_application_requests.present? 
    
    if @user.role == "reporting_head" 
      @leave_application_requests  = LeaveApplicationRequest.where(active: 1)
    end
  end

end

app/views/users/show.html.erb
<% if @user.role == "employee" %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>User Profile</h2>
    </div>
    <div class="col-md-6">
      <%= link_to "Leave Application", new_leave_application_request_path(user_id: @user.id), method: :get, remote: true,:class => 'btn btn-info pull-right'  %>  
    </div>
  </div>
  <div class="row">
    <table id="t01">
      <tr>
        <th>Leave Application Status </th>
        <th>Leaves Credited</th> 
        <th>Leaves Taken</th>
        <th>Current Leave Balance</th>
      </tr>
      <tr>
        <td><%= @user.leave_app_status || "Not Applied" %></td>
        <td><%= @user.leaves_credited.to_i %></td>
        <td><%= @user.leaves_taken.to_i %></td>
        <td><%= @user.leave_balance.to_i  %></td>
      </tr>
    </table>
  </div>
  <h2>Leave Requests</h2>
  <% if @leave_application_requests.length > 0 %>
    <div class="row">
      <table id="t01">
        <tr>
          <th>User Name</th>
          <th>Apply Date</th> 
          <th>Duration</th>
          <th>Leave Status</th>
          <th></th>
          <th></th>
        </tr>
        <% @leave_application_requests.each do |lr| %>
        <tr>
          <td><%= lr.user_name %></td>
          <td><%= lr.apply_date.try(:strftime,"%m/%d/%Y") %></td>
          <td><%= lr.from_date.try(:strftime, "%m/%d/%Y") %>-<%= lr.to_date.try(:strftime, "%m/%d/%Y") %></td>
          <td><%= lr.leave_status %></td>
          <td><%= link_to "Edit", edit_leave_application_request_path(lr, { action_to_do: "edit" }), method: :get, 
            remote: true, :class => 'btn btn-primary pull-right'  %>  </td>
          <td><%= link_to "Cancel", edit_leave_application_request_path(lr, { action_to_do: "cancel"}) , method: :get, 
            remote: true, :class => 'btn btn-danger pull-right'  %> </td>
        </tr>
        <%end%>
      </table>
    </div>
  <%else%>
    <p>No Applications for Leave</p>
  <%end%>
</div>
<%end%>

<%if @user.role == "reporting_head" %>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h2>Reporting Head</h2>
      </div>
    </div>
    <% if @leave_application_requests.length > 0 %>
    <div class="row">
      <table id="t01">
        <tr>
          <th>User Name </th>
          <th>Apply Date</th> 
          <th>Duration</th>
          <th>Leave Status</th>
          <th></th> 
          <th></th>
        </tr>
        <% @leave_application_requests.each do |lr| %>
        <tr>
          <td><%= lr.user_name %></td>
          <td><%= lr.apply_date.try(:strftime,"%m/%d/%Y") %></td>
          <td><%= lr.from_date.try(:strftime, "%m/%d/%Y") %> - <%= lr.to_date.try(:strftime, "%m/%d/%Y") %></td>
          <td><%= lr.leave_status  %></td>
          <% if lr.leave_status != "approved"%>
          <td><%= link_to "Approve", "/leave_application_requests/#{lr.id}?leave_application_request[leave_status]=1&leave_application_request[user_id]=#{@user.id}", method: :put, :class => 'navbar-link pull-right'  %> </td>
          <%else%>
            <td></td>
          <%end%>
          <% if lr.leave_status != "rejected"%>
          <td><%= link_to "Reject", "/leave_application_requests/#{lr.id}?leave_application_request[leave_status]=2&leave_application_request[user_id]=#{@user.id}" , method: :put, :class => 'navbar-link pull-right'  %></td>
          <%else%>
            <td></td>
          <%end%>
        </tr>
        <%end%>
      </table>
    </div>
    <%else%>
      <p>No Leave Requests</p>
    <%end%>
  </div>
<%end%>

<div id='post-content'></div>